# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
  - cron: "0 0 * * *"


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - run: npm install npm@latest -g
    - run: pwd
    - run: ls -ltr
    - run: ls -ltr ..
    - run: ls -l /home
    - run: ls -l /home/runner
    - run: ls -l /home/runner/work/PIE_tools/PIE_tools
    - run: git clone git@github.com:puppetlabs/PIE_tools.git
    # - run: cd nightwatch
    # - run: npm install package.json
    # - run: npm run build --if-present
    - run: npm test
