name: nightwish this would work
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

defaults:
  run:
    working-directory: /home/runner/work/PIE_tools/PIE_tools/nightwatch

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Lets go
        run: |
          echo ${{ secrets.SNOW_USERNAME }}

