name: nightwish this would work
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  install-host:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package.json'

    - run: |
        echo "Finished installing node"


  check-secrets:
    needs: [install-host]
    runs-on: ubuntu-latest

    steps:
      - name: Lets go
        run: |
          echo "my secret OHREALLY== ${{ secrets.OHREALLY }}"
          tree /home/runner/work/

